In [ ]:
#!pip uninstall tensorflow

In [ ]:
#!pip install tensorflow-gpu==2.0.0

In [1]:
import tensorflow as tf
import tensorflow_probability as tfp
from tensorflow.keras import layers
print(tf.__version__)
import time
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
from matplotlib import gridspec
import matplotlib.patches as mpatches
from sklearn.metrics import roc_auc_score
import random
import itertools
from matplotlib.patches import Ellipse
from mpl_toolkits.mplot3d import Axes3D
from scipy.optimize import curve_fit
from sklearn.metrics import confusion_matrix



2.3.0


In [2]:
size = 25

In [3]:
'''config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.compat.v1.Session(config=config)
config = tf.compat.v1.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.95
tf.compat.v1.Session(config=config)'''

'config = tf.compat.v1.ConfigProto()\nconfig.gpu_options.allow_growth = True\nsess = tf.compat.v1.Session(config=config)\nconfig = tf.compat.v1.ConfigProto()\nconfig.gpu_options.per_process_gpu_memory_fraction = 0.95\ntf.compat.v1.Session(config=config)'

![title](擷取.PNG)

In [4]:
def gernate_data(n, nu, seed, range_, multi, size):
    ## normal
    np.random.seed(seed=seed)
    y_train = np.ones((int(n*(1-nu)),))
    mean = np.random.uniform(-5, 5, size)
    cov_  = np.random.uniform(0, 1, (size, size))* 3
    cov = np.dot(cov_.T,cov_)
    x_train = np.random.multivariate_normal(mean, cov, (int(n*(1-nu))))
    x_train = x_train.astype('float32')

    
    
    np.random.seed(seed=seed)
    x_trains_ = None ## normal + outlier
    for i in range(multi):
        mean = np.random.uniform(-range_, range_, size)
        cov_ = np.random.randn(size, size)
        cov = np.dot(cov_.T,cov_)
        x_train_ = np.random.multivariate_normal(mean, cov, (int(n*nu/multi)), check_valid  = 'raise')
        try:
            x_trains_ = np.vstack((x_trains_, x_train_))
        except:
            x_trains_ = x_train_
    ## 畫圖
    '''fig = plt.figure()
    ax = Axes3D(fig)
    ax.scatter(x_train[:, 0], x_train[:, 1],x_train[:, 2], s=0.9, label = 'normal')
    ax.scatter(x_trains_[:,0], x_trains_[:,1], x_trains_[:,2], s=0.9, label = 'outlier')
    plt.legend()
    plt.title('normal + outlier')
    plt.show()'''

    y_trains_ = np.zeros(((len(x_trains_),)))
    x_train_mix = np.vstack((x_trains_, x_train)).astype('float32')
    y_train_mix = np.hstack((y_trains_, y_train)).astype('float32')
    
    return x_train_mix, y_train_mix

## 參數設定

In [5]:

z_dim = 5
h_dim = [10, 5]
regular = 1e-5
max_lr = 1e-6
base_lr = 1e-5


n_epochs = 1000

optimizer = tf.keras.optimizers.Adam(lr = base_lr)

In [6]:
def result_plot (x_train_mix, y_train_mix, ae_model, center, radius = None):
    output = ae_model(x_train_mix, training=False)
    if radius:
        trained_radius = radius.numpy()
    else:
        trained_radius = get_radius(output, nu)
    r = trained_radius**2
    dists = distance(x_train_mix, ae_model, center)
    fig = plt.figure()
    ax = Axes3D(fig)
    ax.scatter(x_train_mix[dists<=r][:,0], x_train_mix[dists<=r][:,1],x_train_mix[dists<=r][:,2] ,s=0.9, label='normal')
    ax.scatter(x_train_mix[dists>=r][:,0], x_train_mix[dists>=r][:,1],x_train_mix[dists>=r][:,2] ,s=0.9, label='anomaly')
    plt.legend()
    plt.show()
    result(dists, y_train_mix.astype(int), r )
    return trained_radius

## 利用aurtoencoder

In [7]:
def make_ae_model():

    inputs = tf.keras.Input(shape=(size,), name='inputs')

    x = tf.keras.layers.Dense(h_dim[0], activation='linear', use_bias=False)(inputs)
    x = tf.keras.layers.Dense(h_dim[1], activation='linear', use_bias=False, name = 'hidden')(x)
    x = tf.keras.layers.Dense(h_dim[0], activation='linear', use_bias=False)(x)
    x = tf.keras.layers.Dense(size, activation='linear', use_bias=False)(x)
    model = tf.keras.Model(inputs=inputs, outputs=x)

    return model

ae_model = make_ae_model()
ae_model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inputs (InputLayer)          [(None, 25)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                250       
_________________________________________________________________
hidden (Dense)               (None, 5)                 50        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_2 (Dense)              (None, 25)                250       
Total params: 600
Trainable params: 600
Non-trainable params: 0
_________________________________________________________________


In [8]:
ae_model = make_ae_model()
ae_model.summary()

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inputs (InputLayer)          [(None, 25)]              0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                250       
_________________________________________________________________
hidden (Dense)               (None, 5)                 50        
_________________________________________________________________
dense_4 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_5 (Dense)              (None, 25)                250       
Total params: 600
Trainable params: 600
Non-trainable params: 0
_________________________________________________________________


## 建構模型

In [9]:
def make_model(model):
    
    model.trainable = True
    x = model.get_layer('hidden').output

    model_out = tf.keras.Model(inputs = model.input, outputs = x)
    
    return model_out

model = make_model(ae_model)
model.summary()

Model: "functional_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inputs (InputLayer)          [(None, 25)]              0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                250       
_________________________________________________________________
hidden (Dense)               (None, 5)                 50        
Total params: 300
Trainable params: 300
Non-trainable params: 0
_________________________________________________________________


## Train deep-SVDD

In [18]:
class train_SVDD():
    
    def __init__(self , objective , encoder, nu , z_dim = z_dim):
        
        self.objective = objective
        self.nu = nu
        self.z_dim = z_dim
        self.encoder = encoder
        self.optimizer = tf.keras.optimizers.Adam(lr = 1e-3, epsilon = 1e-6)
        self.center =  None #np.array(init_center_c(x_train, model = encoder, eps = 0.1))
        
        
    def init_center_c(self, data, eps = 0.1):
    
        #positive = tf.fill([self.z_dim], eps)
        #negative = tf.fill([self.z_dim], -eps)
        c = tf.zeros(shape = [self.z_dim], dtype = tf.float32, name = 'c')
        c = tf.reduce_mean( self.encoder(data, training = False), axis = 0, name = 'outputs') 
        # If c_i is too close to 0, set to +-eps. Reason: a zero unit can be trivially matched with zero weights.

        #c = tf.where(tf.logical_and(tf.less(c, 0), tf.greater(c, -eps)), negative, c)
        #c = tf.where(tf.logical_and(tf.greater(c, 0), tf.less(c, eps)), positive, c)
        
        return c
        
    def get_radius(self,batch_x):
        output = self.encoder(batch_x, training=False)
        dist = tf.reduce_sum(tf.math.square(output - self.center) , axis=1)

        return tfp.stats.percentile(tf.sqrt(dist), (1-self.nu)*100)


    def loss(self, objective, dist, R = None):

        if objective == 'soft-boundary':
            scores = dist - R**2
            avg_loss = R**2 + (1/nu) * tf.reduce_mean(tf.maximum(tf.zeros_like(scores), scores))

        if objective=='deep-SVDD':
            avg_loss = tf.reduce_mean(dist)
        return avg_loss

    @tf.function
    def train_model(self, batch_x, center, objective, R = None):
        with tf.GradientTape() as tape:
            output = self.encoder(batch_x, training=True)
            dist = tf.reduce_sum(tf.math.square(output - self.center) , axis=1)
            output_loss = self.loss(self.objective, dist, R)

        grads = tape.gradient(output_loss, self.encoder.trainable_variables)
        self.optimizer.apply_gradients(zip(grads, self.encoder.trainable_variables))

        return output_loss, dist
    def train(self, train_dataset, x_train, n_epochs = 150, warm_up_n_epochs = 10):
        
        if self.objective == 'soft-boundary':
            self.R = tf.zeros(shape = [1], dtype = tf.float32, name = 'R')
        else:
            self.R = None
        #loss_list = []
        pre_loss = 100
        loss_now = 10
        epoch = 0
        self.center = np.array(self.init_center_c(tf.convert_to_tensor(x_train), eps = 0.1))
        #for epoch in range(n_epochs):
        while abs(pre_loss - loss_now) > 1e-6:
            if (epoch >= warm_up_n_epochs):
                pre_loss = loss_now
            epoch_loss_avg = tf.metrics.Mean()

            for batch, (batch_x) in enumerate(train_dataset):
                loss_, dist = self.train_model(batch_x, self.center, self.objective, self.R )
                epoch_loss_avg(loss_)
                if (self.objective == 'soft-boundary') and (epoch >= warm_up_n_epochs):
                    self.R = self.get_radius(batch_x)
            #loss_list.append(loss_)
            loss_now = epoch_loss_avg.result()
            epoch +=1
        self.encoder.save_weights('oneclass_{}' .format(self.objective))
        #plt.plot(loss_list)
        #plt.show()
        
    def distance(self, data, load_model = True):
        if load_model:
            self.encoder.load_weights('oneclass_{}' .format
                                  (self.objective))
        output = self.encoder(data, training=False)
        dist = tf.reduce_sum(tf.math.square(output - self.center) , axis=1) ## dist**2
        
        return dist
    
    def decide_treshold(self, x_train):
        
        if self.objective == 'soft-boundary':
            radius_end = self.R.numpy()
        else:
            radius_end = self.get_radius(tf.convert_to_tensor(x_train)).numpy()
            
        return float(radius_end)
    def result_plot (self, dists, x_train_mix, radius ):
        r = radius**2
        fig = plt.figure()
        ax = Axes3D(fig)
        ax.scatter(x_train_mix[dists<=r][:,0], x_train_mix[dists<=r][:,1],x_train_mix[dists<=r][:,2] ,s=0.9, label='normal')
        plt.show()
        fig = plt.figure()
        ax = Axes3D(fig)
        ax.scatter(x_train_mix[dists<=r][:,0], x_train_mix[dists<=r][:,1],x_train_mix[dists<=r][:,2] ,s=0.9, label='normal')
        ax.scatter(x_train_mix[dists>=r][:,0], x_train_mix[dists>=r][:,1],x_train_mix[dists>=r][:,2] ,s=0.9, label='anomaly')
        plt.legend()
        plt.show()
    
    def train_result(self, x_train_mix, show_img = False, load_model = True):
        
        radius_end = self.decide_treshold(x_train_mix)
        if show_img:
            dist = self.distance(x_train_mix, load_model = load_model).numpy()
            #self.result_plot (dist, x_train_mix, radius_end )

        return radius_end
    
    def result(self, dist, y_test, radius_end, show_img = False):
        
        y_true = y_test.astype(int)
        scores = dist - radius_end ** 2
        y_prob = 1/dist
        auc = roc_auc_score(y_true, y_prob)
        confusionmatrix = confusion_matrix(y_true, scores<0)
        if show_img:
            print('AUC:', auc)
            print('confusion_matrix:')
            print(confusionmatrix)

        return auc, confusionmatrix 
    
    def test_result(self, x_test_mix, y_test_mix, radius_end, show_img = False, load_model = True):
        
        dist = self.distance(x_test_mix, load_model = load_model).numpy()
        test_auc, confusionmatrix = self.result(dist, y_test_mix, radius_end, show_img = show_img)
        if show_img :
            self.result_plot (dist, x_test_mix, radius_end )

        return test_auc, confusionmatrix 


    

In [19]:
nu = 0.1
x_train_mix, y_train_mix = gernate_data(6000, nu, 16, range_ = 10, multi = 15, size = size)
x_test_mix, y_test_mix = gernate_data(10000, nu, 16,range_ = 10, multi = 15, size = size)
n_samples = len(x_train_mix)


batch_size = 2000
train_buf = x_train_mix.shape[0]
train_dataset = tf.data.Dataset.from_tensor_slices(x_train_mix)
train_dataset = train_dataset.shuffle(buffer_size=train_buf)
train_dataset = train_dataset.batch(batch_size)

In [20]:
result = np.zeros((25, 3))

In [21]:
objective='soft-boundary'
for i in range(25):
    ## 訓練 autoencoder
    pre_time = time.time()
    ae_model = make_ae_model()
    ae_model.compile(optimizer="Adam", loss="mse")
    ae_model.fit(x_train_mix, x_train_mix, epochs = 50, verbose = 0)
    ## 訓練 SVDD
    model = make_model(ae_model)
    SVDD = train_SVDD(objective , model, nu = nu, z_dim = z_dim)
    SVDD.train(train_dataset, x_train_mix)
    radius_end = SVDD.train_result(x_train_mix)
    auc , matrix = SVDD.test_result(x_test_mix, y_test_mix, radius_end)
    train_time = time.time() - pre_time
    print('epoch = ', i, 'auc = ', auc)
    result[i,0] = i
    result[i,1] = auc
    result[i,2] = train_time

epoch =  0 auc =  0.7532803591470258
epoch =  1 auc =  0.7510999438832772
epoch =  2 auc =  0.748390460157127
epoch =  3 auc =  0.7522384960718294
epoch =  4 auc =  0.7538228395061728
epoch =  5 auc =  0.7501763187429854
epoch =  6 auc =  0.7546322671156005
epoch =  7 auc =  0.7572636924803591
epoch =  8 auc =  0.7601794051627385
epoch =  9 auc =  0.7548970819304153
epoch =  10 auc =  0.7582100448933783
epoch =  11 auc =  0.7528151515151517
epoch =  12 auc =  0.7506118406285073
epoch =  13 auc =  0.7594247474747474
epoch =  14 auc =  0.7554609427609428
epoch =  15 auc =  0.7532957912457912
epoch =  16 auc =  0.7529124017957352
epoch =  17 auc =  0.7510489337822672
epoch =  18 auc =  0.751873344556678
epoch =  19 auc =  0.7504547699214366
epoch =  20 auc =  0.7515962962962963
epoch =  21 auc =  0.7553219416386083
epoch =  22 auc =  0.7462099887766553
epoch =  23 auc =  0.7578379910213244
epoch =  24 auc =  0.750203367003367


In [119]:
np.mean(result, 0)

array([ 12.        ,   0.75392784, 274.37576483])

In [120]:
np.std(result, 0)

array([7.21110255e+00, 2.73405723e-03, 2.19528185e+02])

In [121]:
nu = 0.2
x_train_mix, y_train_mix = gernate_data(6000, nu, 16, range_ = 10, multi = 15, size = size)
x_test_mix, y_test_mix = gernate_data(10000, nu, 16,range_ = 10, multi = 15, size = size)
n_samples = len(x_train_mix)


batch_size = 2000
train_buf = x_train_mix.shape[0]
train_dataset = tf.data.Dataset.from_tensor_slices(x_train_mix)
train_dataset = train_dataset.shuffle(buffer_size=train_buf)
train_dataset = train_dataset.batch(batch_size)

In [122]:
result = np.zeros((25, 3))

In [123]:
objective='soft-boundary'
for i in range(25):
    ## 訓練 autoencoder
    pre_time = time.time()
    ae_model = make_ae_model()
    ae_model.compile(optimizer="Adam", loss="mse")
    ae_model.fit(x_train_mix, x_train_mix, epochs = 50, verbose = 0)
    ## 訓練 SVDD
    model = make_model(ae_model)
    SVDD = train_SVDD(objective , model, nu = nu, z_dim = z_dim)
    SVDD.train(train_dataset, x_train_mix)
    radius_end = SVDD.train_result(x_train_mix)
    auc , matrix = SVDD.test_result(x_test_mix, y_test_mix, radius_end)
    train_time = time.time() - pre_time
    print('epoch = ', i, 'auc = ', auc)
    result[i,0] = i
    result[i,1] = auc
    result[i,2] = train_time

epoch =  0 auc =  0.8451887844611529
epoch =  1 auc =  0.8464318922305762
epoch =  2 auc =  0.8451005012531327
epoch =  3 auc =  0.8450069548872179
epoch =  4 auc =  0.8487030388471178
epoch =  5 auc =  0.8482320175438597
epoch =  6 auc =  0.8450221177944862
epoch =  7 auc =  0.844932456140351
epoch =  8 auc =  0.8472800751879699
epoch =  9 auc =  0.847640037593985
epoch =  10 auc =  0.8465110902255639
epoch =  11 auc =  0.8457459899749372
epoch =  12 auc =  0.8458975563909774
epoch =  13 auc =  0.8473439223057645
epoch =  14 auc =  0.8457949874686718
epoch =  15 auc =  0.8466836466165415
epoch =  16 auc =  0.8453066729323309
epoch =  17 auc =  0.8460389097744362
epoch =  18 auc =  0.8458398496240601
epoch =  19 auc =  0.8460388471177944
epoch =  20 auc =  0.845028947368421
epoch =  21 auc =  0.8455559523809525
epoch =  22 auc =  0.8466566416040101
epoch =  23 auc =  0.8461734962406015
epoch =  24 auc =  0.860941290726817


In [124]:
np.mean(result, 0)

array([ 12.        ,   0.84676383, 277.40510846])

In [125]:
np.std(result, 0)

array([7.21110255e+00, 3.06444961e-03, 2.25649560e+02])

In [11]:
nu = 0.3
x_train_mix, y_train_mix = gernate_data(6000, nu, 16, range_ = 10, multi = 15, size = size)
x_test_mix, y_test_mix = gernate_data(10000, nu, 16,range_ = 10, multi = 15, size = size)
n_samples = len(x_train_mix)


batch_size = 2000
train_buf = x_train_mix.shape[0]
train_dataset = tf.data.Dataset.from_tensor_slices(x_train_mix)
train_dataset = train_dataset.shuffle(buffer_size=train_buf)
train_dataset = train_dataset.batch(batch_size)

In [12]:
objective='soft-boundary'
result = np.zeros((25, 3))
for i in range(25):
    ## 訓練 autoencoder
    pre_time = time.time()
    ae_model = make_ae_model()
    ae_model.compile(optimizer="Adam", loss="mse")
    ae_model.fit(x_train_mix, x_train_mix, epochs = 50, verbose = 0)
    ## 訓練 SVDD
    model = make_model(ae_model)
    SVDD = train_SVDD(objective , model, nu = nu, z_dim = z_dim)
    SVDD.train(train_dataset, x_train_mix)
    radius_end = SVDD.train_result(x_train_mix)
    auc , matrix = SVDD.test_result(x_test_mix, y_test_mix, radius_end)
    train_time = time.time() - pre_time
    print('epoch = ', i, 'auc = ', auc)
    result[i,0] = i
    result[i,1] = auc
    result[i,2] = train_time

epoch =  0 auc =  0.8527315476190477
epoch =  1 auc =  0.8528015238095239
epoch =  2 auc =  0.8515214285714285
epoch =  3 auc =  0.8591518571428571
epoch =  4 auc =  0.8522919999999999
epoch =  5 auc =  0.8523417142857141
epoch =  6 auc =  0.8515844523809524
epoch =  7 auc =  0.852648238095238
epoch =  8 auc =  0.8514910476190477
epoch =  9 auc =  0.8550736666666667
epoch =  10 auc =  0.8521324761904763
epoch =  11 auc =  0.8523225714285714
epoch =  12 auc =  0.8518956904761905
epoch =  13 auc =  0.8509216666666668
epoch =  14 auc =  0.8526380476190476
epoch =  15 auc =  0.8519092857142858
epoch =  16 auc =  0.8516865714285715
epoch =  17 auc =  0.8517850476190477
epoch =  18 auc =  0.851663
epoch =  19 auc =  0.8520766666666667
epoch =  20 auc =  0.8516358571428572
epoch =  21 auc =  0.8525156666666667
epoch =  22 auc =  0.8512982380952381
epoch =  23 auc =  0.8518354761904763
epoch =  24 auc =  0.8528177619047619


In [13]:
np.mean(result, 0)

array([ 12.        ,   0.85243086, 454.04103101])

In [14]:
np.std(result, 0)

array([7.21110255e+00, 1.57451405e-03, 3.64634377e+02])